import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import matplotlib.transforms as transforms

def CIEllipse(mean, cov, ax, n_std=2.0, facecolor='none', **kwargs):
    """
    Create a plot of the covariance confidence ellipse of `x` and `y`

    Parameters
    ----------
    x, y : array_like, shape (n, )
        Input data.

    ax : matplotlib.axes.Axes
        The axes object to draw the ellipse into.

    n_std : float
        The number of standard deviations to determine the ellipse's radiuses.

    Returns
    -------
    matplotlib.patches.Ellipse

    Other parameters
    ----------------
    kwargs : `~matplotlib.patches.Patch` properties
    """

    pearson = cov[0, 1]/np.sqrt(cov[0, 0] * cov[1, 1])
    # Using a special case to obtain the eigenvalues of this
    # two-dimensionl dataset.
    ell_radius_x = np.sqrt(1 + pearson)
    ell_radius_y = np.sqrt(1 - pearson)
    ellipse = Ellipse((0, 0),
        width=ell_radius_x * 2,
        height=ell_radius_y * 2,
        facecolor=facecolor,
        **kwargs)

    # Calculating the stdandard deviation of x from
    # the squareroot of the variance and multiplying
    # with the given number of standard deviations.
    scale_x = np.sqrt(cov[0, 0]) * n_std
    mean_x = mean[0]

    # calculating the stdandard deviation of y ...
    scale_y = np.sqrt(cov[1, 1]) * n_std
    mean_y = mean[1]

    transf = transforms.Affine2D() \
        .rotate_deg(45) \
        .scale(scale_x, scale_y) \
        .translate(mean_x, mean_y)

    ellipse.set_transform(transf + ax.transData)
    return ax.add_patch(ellipse)


def CIEllipse_data(x, ax, n_std=3.0, facecolor='none', **kwargs):
    cov = np.cov(x, rowvar=False)
    mean = np.mean(x, axis=0)
    CIEllipse(mean, cov, ax, n_std=3.0, facecolor='none', **kwargs)




#### Generated by GPT
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse

def plot_cov_ellipse(cov, mean, n_std=2.0, ax=None, **kwargs):
    """
    Plots an ellipse representing the covariance matrix.
    
    Args:
        cov: 2x2 covariance matrix
        mean: 2D mean vector
        n_std: Number of standard deviations (default 2σ)
        ax: matplotlib Axes
    """
    if ax is None:
        ax = plt.gca()
    
    # Eigenvalues and eigenvectors
    vals, vecs = np.linalg.eigh(cov)
    
    # Sort eigenvalues descending
    order = vals.argsort()[::-1]
    vals, vecs = vals[order], vecs[:, order]
    
    # Compute angle between x-axis and largest eigenvector
    theta = np.degrees(np.arctan2(*vecs[:, 0][::-1]))
    
    # Width and height are "full lengths" of ellipse axes
    width, height = 2 * n_std * np.sqrt(vals)
    
    ellipse = Ellipse(xy=mean, width=width, height=height, angle=theta, **kwargs)
    ax.add_patch(ellipse)
    return ax

# Example usage
mean = [0, 0]
cov = [[3, 1], [1, 2]]

fig, ax = plt.subplots()
plot_cov_ellipse(cov, mean, n_std=2, ax=ax, edgecolor='red')
ax.scatter(*mean, color='blue')
ax.set_xlim(-10, 10)
ax.set_ylim(-10, 10)
plt.grid()
plt.show()



